### ISSUE TITLE
Not root

### ISSUE THREAD

**Issue by Silvers12** [joe-speedboat/docker.xfce-vnc#1]
Hi !
Thx for your work.
Can you explain how can i have root access ? Because i can't install anything.
I need sudo for apt install but can't install sudo.
Thx ;)
![image](https://user-images.githubusercontent.com/9714780/135150727-169c0bdf-94be-46f0-8d45-53ef4f0433ad.png)

I can use su, but i don't know the password ...

**Comment by joe-speedboat** [comment]
Hi 
Change the user or install software in a container is not the idea of docker. It's not worth discussing it, just believe me.
If you need to install software, make a fork of the repo and edit the Dockerfile to suite your needs. 
And build it locally on your host, then you can start the image with your needed software in it.
BR Chris
