### ISSUE TITLE
SyntaxError in logging.js

### ISSUE THREAD

**Issue by dmitrijszaharovs** [joe-speedboat/docker.xfce-vnc#3]
Hello!
Just started Docker container, went to `http://myremotehost:6901/?password=mypass/`
and got the following red alert:
```
SyntaxError: The requested module '../core/util/logging.js' does not provide an export named 'initLogging'
...
http://myremotehost:6901:6901/app/webutil.js:9:10
```
What could it be?

**Comment by joe-speedboat** [comment]
Hi, can you please:
Provide me the Docker command you used to start the container?
Can you test acessing just: http://myremotehost:6901 and thell me if that works?
I just tested with the cmd in the readme and it worked:
docker run --env VNC_PW=secure. --env DEBUG=true --publish 5901:5901 --publish 6901:6901 christian773/xfce-vnc:latest
Do you have any browser plugins enabled?
BR Chris

**Comment by dmitrijszaharovs** [comment]
Thanks @joe-speedboat  for answer and ideas:
I tried to start my Chrome in incognito mode (of course I've got a number of plugins)
and - voilà! 
Started with the following command line:
```
docker run --network=host --env VNC_PW=mysuperpass --env DEBUG=true --publish 5901:5901 --publish 6901:6901 christian773/xfce-vnc:latest
```
(on start saw some errors, although...)

Works both with 
`http://myremotehost:6901/?password=mysuperpass/ `
and 
`http://myremotehost:6901`

So, looks like browser/plugin(s) issue.

Thanks.
