### ISSUE TITLE
Firefox Profile Corrupted

### ISSUE THREAD

**Issue by tmunsch** [joe-speedboat/docker.xfce-vnc#4]
Can't run Firefox for some reason and need sudo to fix it but don't have the password for the sudo user. Any ideas? Great work BTW!

**Comment by tmunsch** [comment]
Disregard, I will work on this in my free time. Thank you for doing this. It's a huge headstart.

**Comment by joe-speedboat** [comment]
Hi @tmunsch 
Hmm, I run this images in OKD 4.x, Docker and Podman on Centos7 and AlmaLinux8, never had a problem.
Changing UID's and modifing the image is not part of the Docker concept.
Users HomeDir itself is writable, If you need to modify this image, you need to clone the Repo and create a pull request.
If the modification is pointing to a fix for this issue, I will pull it.

But please alway give as much information as possible when you open a bug request, at least all the information for me to reproduce the bug in my environment. If not, I will not really be able to support your needs.

Cheers Chris
