### ISSUE TITLE
README FIRST

### ISSUE THREAD

**Issue by joe-speedboat** [joe-speedboat/docker.xfce-vnc#5]
Hi out there!
Thanks for using and contributing to OpenSource.

Before you open a Ticket, please think if you understand what you are asking.
I got many people asking for root rights, sudo, ... or using apt within the image ...

I will close such requests without answering, because of missing time and mood :-)

**Comment by enterprisium** [comment]
i am sorry but i dont knw where i mistaken the system. but a question is same as you mentioned. how can i use sudo in image. at hf.

**Comment by joe-speedboat** [comment]
.

**Comment by joe-speedboat** [comment]
.
