### ISSUE TITLE
Unstable VSCode behavior

### ISSUE THREAD

**Issue by jrbe228** [joe-speedboat/docker.xfce-vnc#6]
VSCode is very unstable, frequently crashing when I attempt to work with Extensions or Terminal. Behavior improves somewhat when launching as `code --disable-gpu --no-sandbox` rather than simply `code`. Either way it still crashes often with error code 133 or error code 4. I can add more details if needed but I think this will be easy to reproduce.

**Comment by joe-speedboat** [comment]
Sorry wrong Project
